#!/usr/bin/env node
//
// Downloads the codex's typefaces from Google Fonts and self-hosts them.
//
//   node frame/fetch-fonts.mjs
//
// ---------------------------------------------------------------------------
// Why self-host rather than link the CDN
// ---------------------------------------------------------------------------
// A <link> to fonts.googleapis.com means every reader's browser announces itself
// to a third party on every page load. Self-hosting removes that entirely: no
// third-party request, no privacy question, the site works offline, and nothing
// breaks if the CDN changes a URL. The cost is a few hundred KB of woff2 in the
// repository, which is a fair trade.
//
// All four families are openly licensed (see LICENSES.md, generated alongside),
// so redistribution here is permitted. None imitates Games Workshop's own brand
// typography — these are genre-appropriate independent faces.
//
// Only the `latin` and `latin-ext` subsets are kept. The codex is written in
// English with occasional accented names; shipping Cyrillic and Greek would
// multiply the payload for no reader.
//
// Re-run this to update or re-fetch. It rewrites fonts.css and LICENSES.md.

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './lib.mjs';

const FONT_DIR = join(ROOT, 'theme', 'overrides', 'assets', 'fonts');
const CSS_OUT = join(ROOT, 'theme', 'overrides', 'assets', 'stylesheets', 'fonts.css');

// A modern UA is required: Google Fonts serves woff2 only to browsers it
// believes support it, and falls back to far larger formats otherwise.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

// Option 06 — "Ecclesiarchy & Forge".
const FAMILIES = [
  {
    family: 'Grenze Gotisch',
    spec: 'Grenze+Gotisch:wght@100..900',
    slug: 'grenze-gotisch',
    role: 'Chapter titles. Blackletter — the cathedral half of the Imperium.',
    licence: 'SIL Open Font License 1.1',
  },
  {
    family: 'Big Shoulders Stencil Display',
    spec: 'Big+Shoulders+Stencil+Display:wght@100..900',
    slug: 'big-shoulders-stencil',
    role: 'Section headings, eyebrows, badges, all UI labels. Industrial stencil — the factory-floor half.',
    licence: 'SIL Open Font License 1.1',
  },
  {
    family: 'Vollkorn',
    spec: 'Vollkorn:ital,wght@0,400..900;1,400..900',
    slug: 'vollkorn',
    role: 'Body prose. Sturdy and slightly rough — grimdark without fighting the reader across 250,000 words.',
    licence: 'SIL Open Font License 1.1',
  },
  {
    family: 'Share Tech Mono',
    spec: 'Share+Tech+Mono',
    slug: 'share-tech-mono',
    role: 'The citation apparatus, registries and source keys. Cogitator output.',
    licence: 'SIL Open Font License 1.1',
  },
];

function curl(url, outFile) {
  const args = ['-sS', '--compressed', '--max-time', '60', '--retry', '2',
                '-A', UA, '-w', '%{http_code}'];
  if (outFile) args.push('-o', outFile);
  const res = execFileSync('curl', [...args, url], { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
  if (outFile) return { status: Number(res.trim()) };
  const status = Number(res.slice(-3));
  return { status, body: res.slice(0, -3) };
}

/** Parse Google's CSS into { subset, style, weight, unicodeRange, url } blocks. */
function parseFaces(css) {
  const faces = [];
  // Google emits "/* subset */" immediately before each @font-face.
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/gi;
  for (const m of css.matchAll(re)) {
    const subset = m[1];
    const block = m[2];
    const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    if (!url) continue;
    faces.push({
      subset,
      style: /font-style:\s*([^;]+);/.exec(block)?.[1].trim() ?? 'normal',
      weight: /font-weight:\s*([^;]+);/.exec(block)?.[1].trim() ?? '400',
      unicodeRange: /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim() ?? null,
      url,
    });
  }
  return faces;
}

mkdirSync(FONT_DIR, { recursive: true });

const cssParts = [
  '/* ==========================================================================',
  '   Self-hosted typefaces — GENERATED by frame/fetch-fonts.mjs. Do not edit.',
  '   ==========================================================================',
  '',
  '   Option 06, "Ecclesiarchy & Forge": two display registers, because the',
  '   Imperium is a gothic theocracy running on assembly lines. Blackletter for',
  '   chapter titles, industrial stencil for every heading and label.',
  '',
  '   Served from this repository, not a CDN — no third-party request on any page',
  '   load. Licences: assets/fonts/LICENSES.md',
  '   ========================================================================== */',
  '',
];

let total = 0;
const report = [];

for (const fam of FAMILIES) {
  const { status, body } = curl(`https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`);
  if (status !== 200) {
    console.error(`  ! ${fam.family}: CSS request failed HTTP ${status}`);
    process.exitCode = 1;
    continue;
  }

  const faces = parseFaces(body).filter(f => KEEP_SUBSETS.has(f.subset));
  if (!faces.length) {
    console.error(`  ! ${fam.family}: no latin faces found in response`);
    process.exitCode = 1;
    continue;
  }

  let famBytes = 0;
  cssParts.push(`/* ---- ${fam.family} — ${fam.role} ---- */`);

  for (const f of faces) {
    const italic = f.style.includes('italic');
    const name = `${fam.slug}-${f.subset}${italic ? '-italic' : ''}.woff2`;
    const dest = join(FONT_DIR, name);

    const dl = curl(f.url, dest);
    if (dl.status !== 200) {
      console.error(`  ! ${name}: HTTP ${dl.status}`);
      process.exitCode = 1;
      continue;
    }
    const bytes = statSync(dest).size;
    famBytes += bytes;
    total += bytes;

    cssParts.push('@font-face {');
    cssParts.push(`  font-family: "${fam.family}";`);
    cssParts.push(`  font-style: ${f.style};`);
    cssParts.push(`  font-weight: ${f.weight};`);
    cssParts.push('  font-display: swap;');
    cssParts.push(`  src: url("../fonts/${name}") format("woff2");`);
    if (f.unicodeRange) cssParts.push(`  unicode-range: ${f.unicodeRange};`);
    cssParts.push('}');
  }
  cssParts.push('');

  report.push({ family: fam.family, faces: faces.length, kb: Math.round(famBytes / 1024) });
  console.log(`  ok  ${fam.family.padEnd(30)} ${faces.length} face(s)  ${Math.round(famBytes / 1024)} KB`);
}

writeFileSync(CSS_OUT, cssParts.join('\n') + '\n', 'utf8');

// --- licences -------------------------------------------------------------
const lic = [
  '# Font licences',
  '',
  'The typefaces in this directory are redistributed with this project under their',
  'own open licences. They are self-hosted so that the site makes no third-party',
  'request on page load.',
  '',
  'None of these faces imitates Games Workshop\'s brand typography. They are',
  'independent, openly licensed families chosen for genre suitability.',
  '',
  '| Family | Licence | Role |',
  '|---|---|---|',
  ...FAMILIES.map(f => `| ${f.family} | ${f.licence} | ${f.role} |`),
  '',
  '## SIL Open Font License 1.1',
  '',
  'Full licence text: <https://openfontlicense.org/open-font-license-official-text/>',
  '',
  'Each family is also published with its licence in the Google Fonts repository,',
  'e.g. <https://github.com/google/fonts/blob/main/ofl/vollkorn/OFL.txt>.',
  '',
  'Under OFL 1.1 these fonts may be used, studied, modified and redistributed',
  'freely, including bundled with a work such as this one. The Reserved Font Names',
  'may not be used for modified versions — no font here has been modified; the',
  'woff2 files are the upstream Google Fonts builds, subset to `latin` and',
  '`latin-ext` by Google\'s own service.',
  '',
  '## Regenerating',
  '',
  '```bash',
  'node frame/fetch-fonts.mjs',
  '```',
  '',
  'That rewrites `assets/stylesheets/fonts.css` and this file.',
  '',
];
writeFileSync(join(FONT_DIR, 'LICENSES.md'), lic.join('\n'), 'utf8');

console.log(`\n  ${report.length} famil(ies), ${Math.round(total / 1024)} KB total`);
console.log('  wrote assets/stylesheets/fonts.css and assets/fonts/LICENSES.md\n');
