// Shared loading and parsing for the codex toolchain.
// See frame/schema.md — that document is the contract, this is its implementation.

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

export const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const BOOK_DIR = join(ROOT, 'book');
export const DATA_DIR = join(ROOT, 'data');

// ---------------------------------------------------------------------------
// Depth bands — PROMPT.md §7. Derived from the ID, never stored in a file.
// ---------------------------------------------------------------------------

export const BANDS = {
  full: { min: 400, max: 500 },
  medium: { min: 350, max: 450 },
  reference: { min: 300, max: 400 },
};

const FULL_VOLUMES = new Set(['I', 'III', 'IV', 'V', 'VI']);

export function depthFor({ volume, titleNo }) {
  if (FULL_VOLUMES.has(volume)) return 'full';
  if (volume === 'II' || volume === 'VII') return 'medium';
  if (volume === 'VIII') return titleNo === 1 ? 'full' : 'medium';
  if (volume === 'IX' || volume === 'APX') return 'reference';
  return null; // unknown volume — the validator reports this
}

// ---------------------------------------------------------------------------
// IDs
// ---------------------------------------------------------------------------

const CHAPTER_ID = /^(I|II|III|IV|V|VI|VII|VIII|IX|APX)\.T(\d+)\.Ch(\d+)$/;

export function parseChapterId(id) {
  const m = CHAPTER_ID.exec(id ?? '');
  if (!m) return null;
  return { volume: m[1], titleNo: Number(m[2]), chapterNo: Number(m[3]) };
}

export const SLUG_OK = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// ---------------------------------------------------------------------------
// Markup recognised in prose. One family, all of it validated.
// ---------------------------------------------------------------------------

// [[target]] or [[target|display text]]
export const LINK_RE = /\[\[([^\]|\n]+?)(?:\|([^\]\n]+?))?\]\]/g;

// [^source-id] — but NOT a footnote *definition* line, which starts at column 0
// as "[^id]:" and is generated by the build rather than written by hand.
export const CITE_RE = /\[\^([A-Za-z0-9][A-Za-z0-9._-]*)\](?!:)/g;

// ---------------------------------------------------------------------------
// Registries
// ---------------------------------------------------------------------------

export function loadYaml(path) {
  const raw = readFileSync(path, 'utf8');
  return YAML.parse(raw) ?? {};
}

export function loadRegistries() {
  return {
    sources: loadYaml(join(DATA_DIR, 'sources.yaml')),
    glossary: loadYaml(join(DATA_DIR, 'glossary.yaml')),
    subjects: loadYaml(join(DATA_DIR, 'subjects.yaml')),
    contradictions: loadYaml(join(DATA_DIR, 'contradictions.yaml')),
  };
}

// ---------------------------------------------------------------------------
// Chapter files
// ---------------------------------------------------------------------------

function walk(dir, out = []) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries.sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry.endsWith('.md')) out.push(full);
  }
  return out;
}

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

// A `##` heading with an explicit {#anchor}, per frame/schema.md §4.
const HEADING_RE = /^##\s+(.+?)\s*\{#([A-Za-z0-9-]+)\}\s*$/;

/** Words of prose, ignoring markup that a reader does not read. */
export function countWords(text) {
  const cleaned = text
    .replace(/```[\s\S]*?```/g, ' ')            // fenced code
    .replace(/^\s{0,3}>\s?/gm, ' ')             // blockquote markers
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')      // images
    .replace(LINK_RE, (_m, target, text) => text ?? target.replace(/^[sg]:/, ''))
    .replace(CITE_RE, ' ')                       // citation markers are not prose
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')    // inline links keep their text
    .replace(/[*_`~#|]/g, ' ');
  const words = cleaned.match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu);
  return words ? words.length : 0;
}

/**
 * Parse a Chapter file into frontmatter, body, and the Sections found in the body.
 * Returns { ok: false, error } for a file that is not a Chapter at all.
 */
export function parseChapter(file) {
  const raw = readFileSync(file, 'utf8');
  const rel = relative(ROOT, file).split(sep).join('/');
  const fm = FRONTMATTER_RE.exec(raw);
  if (!fm) return { ok: false, rel, error: 'no YAML frontmatter' };

  let front;
  try {
    front = YAML.parse(fm[1]) ?? {};
  } catch (e) {
    return { ok: false, rel, error: `unparseable frontmatter: ${e.message}` };
  }
  if (!front.id) return { ok: false, rel, error: 'frontmatter has no `id`' };

  const body = raw.slice(fm[0].length);
  const lines = body.split(/\r?\n/);
  // Lines consumed by the frontmatter, so reported line numbers match the actual
  // file rather than an offset into the body.
  const bodyOffset = (fm[0].match(/\n/g) ?? []).length;

  // Slice the body at `##` headings so each Section's words are its own.
  const found = [];
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) return;
    const h = HEADING_RE.exec(line);
    if (h) found.push({ name: h[1].trim(), slug: h[2], start: i });
    else if (/^##\s+/.test(line)) found.push({ name: line.replace(/^##\s+/, '').trim(), slug: null, start: i });
  });

  found.forEach((s, i) => {
    const end = i + 1 < found.length ? found[i + 1].start : lines.length;
    s.text = lines.slice(s.start + 1, end).join('\n');
    s.words = countWords(s.text);
  });

  return { ok: true, rel, file, front, body, bodyOffset, sections: found };
}

export function loadChapters() {
  return walk(BOOK_DIR).map(parseChapter);
}

/**
 * Collect every [[...]] and [^...] in a body.
 * `offset` is the chapter's bodyOffset, so reported lines point into the real file.
 */
export function collectMarkup(body, offset = 0) {
  const links = [];
  const cites = [];
  body.split(/\r?\n/).forEach((line, i) => {
    const at = offset + i + 1;
    for (const m of line.matchAll(LINK_RE)) {
      links.push({ target: m[1].trim(), text: m[2]?.trim() ?? null, line: at });
    }
    for (const m of line.matchAll(CITE_RE)) {
      cites.push({ id: m[1], line: at });
    }
  });
  return { links, cites };
}
