// Shared loading and parsing for the codex toolchain.
// See frame/schema.md — that document is the contract, this is its implementation.

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

export const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const BOOK_DIR = join(ROOT, 'book');
export const DATA_DIR = join(ROOT, 'data');

// ---------------------------------------------------------------------------
// Depth bands — PROMPT.md §7. Derived from the ID, never stored in a file.
// ---------------------------------------------------------------------------

export const BANDS = {
  full: { min: 400, max: 500 },
  medium: { min: 350, max: 450 },
  reference: { min: 300, max: 400 },
};

const FULL_VOLUMES = new Set(['I', 'III', 'IV', 'V', 'VI']);

export function depthFor({ volume, titleNo }) {
  if (FULL_VOLUMES.has(volume)) return 'full';
  if (volume === 'II' || volume === 'VII') return 'medium';
  if (volume === 'VIII') return titleNo === 1 ? 'full' : 'medium';
  if (volume === 'IX' || volume === 'APX') return 'reference';
  return null; // unknown volume — the validator reports this
}

// ---------------------------------------------------------------------------
// IDs
// ---------------------------------------------------------------------------

const CHAPTER_ID = /^(I|II|III|IV|V|VI|VII|VIII|IX|APX)\.T(\d+)\.Ch(\d+)$/;

export function parseChapterId(id) {
  const m = CHAPTER_ID.exec(id ?? '');
  if (!m) return null;
  return { volume: m[1], titleNo: Number(m[2]), chapterNo: Number(m[3]) };
}

export const SLUG_OK = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// ---------------------------------------------------------------------------
// Markup recognised in prose. One family, all of it validated.
// ---------------------------------------------------------------------------

// [[target]] or [[target|display text]]
export const LINK_RE = /\[\[([^\]|\n]+?)(?:\|([^\]\n]+?))?\]\]/g;

// [^source-id] — but NOT a footnote *definition* line, which starts at column 0
// as "[^id]:" and is generated by the build rather than written by hand.
export const CITE_RE = /\[\^([A-Za-z0-9][A-Za-z0-9._-]*)\](?!:)/g;

// ---------------------------------------------------------------------------
// Registries
// ---------------------------------------------------------------------------

export function loadYaml(path) {
  const raw = readFileSync(path, 'utf8');
  return YAML.parse(raw) ?? {};
}

export function loadRegistries() {
  return {
    sources: loadYaml(join(DATA_DIR, 'sources.yaml')),
    glossary: loadYaml(join(DATA_DIR, 'glossary.yaml')),
    subjects: loadYaml(join(DATA_DIR, 'subjects.yaml')),
    contradictions: loadYaml(join(DATA_DIR, 'contradictions.yaml')),
  };
}

// ---------------------------------------------------------------------------
// Chapter files
// ---------------------------------------------------------------------------

function walk(dir, out = []) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries.sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry.endsWith('.md')) out.push(full);
  }
  return out;
}

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

// A `##` heading with an explicit {#anchor}, per frame/schema.md §4.
const HEADING_RE = /^##\s+(.+?)\s*\{#([A-Za-z0-9-]+)\}\s*$/;

/** Words of prose, ignoring markup that a reader does not read. */
export function countWords(text) {
  const cleaned = text
    .replace(/```[\s\S]*?```/g, ' ')            // fenced code
    .replace(/^\s{0,3}>\s?/gm, ' ')             // blockquote markers
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')      // images
    .replace(LINK_RE, (_m, target, text) => text ?? target.replace(/^[sg]:/, ''))
    .replace(CITE_RE, ' ')                       // citation markers are not prose
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')    // inline links keep their text
    .replace(/[*_`~#|]/g, ' ');
  const words = cleaned.match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu);
  return words ? words.length : 0;
}

/**
 * Parse a Chapter file into frontmatter, body, and the Sections found in the body.
 * Returns { ok: false, error } for a file that is not a Chapter at all.
 */
export function parseChapter(file) {
  const raw = readFileSync(file, 'utf8');
  const rel = relative(ROOT, file).split(sep).join('/');
  const fm = FRONTMATTER_RE.exec(raw);
  if (!fm) return { ok: false, rel, error: 'no YAML frontmatter' };

  let front;
  try {
    front = YAML.parse(fm[1]) ?? {};
  } catch (e) {
    return { ok: false, rel, error: `unparseable frontmatter: ${e.message}` };
  }
  if (!front.id) return { ok: false, rel, error: 'frontmatter has no `id`' };

  const body = raw.slice(fm[0].length);
  const lines = body.split(/\r?\n/);
  // Lines consumed by the frontmatter, so reported line numbers match the actual
  // file rather than an offset into the body.
  const bodyOffset = (fm[0].match(/\n/g) ?? []).length;

  // Slice the body at `##` headings so each Section's words are its own.
  const found = [];
  let inFence = false;
  lines.forEach((line, i) => {
    if (/^\s*```/.test(line)) inFence = !inFence;
    if (inFence) return;
    const h = HEADING_RE.exec(line);
    if (h) found.push({ name: h[1].trim(), slug: h[2], start: i });
    else if (/^##\s+/.test(line)) found.push({ name: line.replace(/^##\s+/, '').trim(), slug: null, start: i });
  });

  found.forEach((s, i) => {
    const end = i + 1 < found.length ? found[i + 1].start : lines.length;
    s.text = lines.slice(s.start + 1, end).join('\n');
    s.words = countWords(s.text);
  });

  return { ok: true, rel, file, front, body, bodyOffset, sections: found };
}

export function loadChapters() {
  return walk(BOOK_DIR).map(parseChapter);
}

// ---------------------------------------------------------------------------
// Glossary surface forms — how a registered term actually appears in prose
// ---------------------------------------------------------------------------
//
// A drift audit found three terms that looked unused and were not: the registry
// holds "Tomb World" while the prose only ever writes "Tomb Worlds"; "Tetrarch of
// Ultramar" against a prose that says plain "Tetrarch"; "Dolmen Gate" against
// "dolmen gates". Matching the registered string alone misses the majority of real
// occurrences, so both the validator and the build expand each entry into the forms
// a writer would actually type.

const LEADING_ARTICLE = /^(?:the|a|an)\s+/i;

/** Plural of the final word only. "Tomb World" -> "Tomb Worlds". */
function pluralise(phrase) {
  const m = /^(.*?)([\p{L}][\p{L}'’]*)$/u.exec(phrase);
  if (!m) return [];
  const [, head, last] = m;
  if (/(?:s|x|z|ch|sh)$/i.test(last)) return [`${head}${last}es`];
  if (/[^aeiou]y$/i.test(last)) return [`${head}${last.slice(0, -1)}ies`];
  return [`${head}${last}s`];
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Map of lowercased surface form -> glossary key.
 *
 * Forms shorter than three characters are dropped: they generate far more false
 * positives in running prose than they could ever be worth.
 *
 * `variants` is deliberately EXCLUDED by default, because it answers a different
 * question. As an alias for the glossary page and for search, "psychic" for psyker
 * or "the Force" for psionics is helpful. As an auto-link trigger it is a disaster:
 * the first run of this marker used variants and produced 36 wrong links — every
 * adjectival "psychic", every "force" and "forces" in a book about warfare, and
 * every material "tithe" pointed at the psyker tithe.
 *
 * An entry that genuinely has a second spelling worth marking says so explicitly
 * with `mark: [...]`. Passing `variants: true` includes them anyway, which is what
 * the validator wants when asking the looser question "does this entry appear in
 * the book under ANY of its names?".
 */
export function glossaryForms(glossary, { variants = false } = {}) {
  const byForm = new Map();
  // Forms that must only match when the prose capitalises them. See below.
  const capitalOnly = new Set();
  const declaredVerbatim = new Set();

  for (const [key, entry] of Object.entries(glossary)) {
    const base = [
      entry?.term ?? key,
      ...(entry?.mark ?? []),
      ...(variants ? (entry?.variants ?? []) : []),
    ].filter(Boolean).map(String);
    const forms = new Set();
    for (const b of base) {
      const declared = b.trim();
      const stripped = declared.replace(LEADING_ARTICLE, '');
      // Only a form the author actually wrote in lower case earns the lower-case
      // exemption below. Declaring "the Warp" must not license "the warp".
      if (/^[a-z]/.test(stripped)) declaredVerbatim.add(declared.toLowerCase());

      for (const variant of new Set([declared, stripped])) {
        if (variant.length < 3) continue;
        forms.add(variant);
        for (const p of pluralise(variant)) forms.add(p);
      }

      // A proper noun may match only where the prose capitalises it. Matched
      // case-insensitively, "the Conduit" put the Astropathic Conduit's definition
      // on "bundles of cables, wires and conduits"; "the Purging" put the atomic
      // bombardment of Krieg on "he was purging their souls"; and once this covered
      // the subject registry too, "the Old Ones" put the galaxy's first sentient
      // species on "new islands rising and old ones being subsumed".
      //
      // That last one refuted an earlier version of this rule, which applied only to
      // SINGLE-word forms on the reasoning that a multi-word name could not collide
      // with ordinary English. "old ones" collides. The test is therefore what the
      // name IS rather than how many words it has: if it reads as a proper noun,
      // every form derived from it requires capitals.
      if (/^[A-Z]/.test(stripped)) {
        for (const v of [declared, stripped, ...pluralise(declared), ...pluralise(stripped)]) {
          if (v.length < 3) continue;
          capitalOnly.add(v.toLowerCase());
        }
      }
    }
    for (const form of forms) {
      const norm = form.toLowerCase();
      // First entry to claim a form keeps it. A genuine collision across two
      // entries is a registry error, and Pass 4 already fails the build on it.
      if (!byForm.has(norm)) byForm.set(norm, key);
    }
  }

  // An entry that deliberately declares a lowercase form — `mark: [warp]` —
  // means it, and outranks the inference above.
  for (const form of declaredVerbatim) capitalOnly.delete(form);

  byForm.capitalOnly = capitalOnly;
  return byForm;
}

/**
 * Does this match respect the capitalisation its surface form requires?
 * A no means the prose used an ordinary English word that happens to be a
 * registered proper noun with its article removed.
 */
export function matchCaseOk(byForm, matched) {
  const norm = matched.toLowerCase();
  if (!byForm.capitalOnly?.has(norm)) return true;
  // Look past a leading article, so "the Awakening" passes and "the awakening of
  // Ynnead" does not. Judging the raw first character would accept both, because
  // a sentence-initial "The" is capitalised whatever follows it.
  return /^[A-Z]/.test(matched.replace(LEADING_ARTICLE, ''));
}

/** One alternation over every surface form, longest first so "C'tan Shard" beats "C'tan". */
export function glossaryRegex(byForm) {
  const alternatives = [...byForm.keys()]
    .sort((a, b) => b.length - a.length || a.localeCompare(b))
    // The sources are inconsistent about which apostrophe they use, and so is prose
    // written from them. Accept either for any form containing one.
    .map((f) => escapeRe(f).replace(/['’]/g, "['’]"));
  return new RegExp(`(?<![\\p{L}\\p{N}\\-])(${alternatives.join('|')})(?![\\p{L}\\p{N}\\-])`, 'giu');
}

/**
 * Byte ranges of a body that are not running prose, and must never be marked up:
 * code, headings, admonition title lines, generated footnote definitions, our own
 * link syntax, existing links, attribute blocks and raw HTML.
 *
 * Admonition BODIES are deliberately not protected — they are prose the reader
 * reads, and a term's first use is often inside a disputed-facts callout.
 */
export function protectedRanges(text) {
  const ranges = [];
  const add = (re) => {
    for (const m of text.matchAll(re)) ranges.push([m.index, m.index + m[0].length]);
  };
  add(/```[\s\S]*?```/g);
  add(/`[^`\n]*`/g);
  add(/^#{1,6}\s.*$/gm);
  add(/^\s*!!!.*$/gm);
  add(/^\s*\[\^[^\]]+\]:.*$/gm);
  add(/\[\[[^\]]*\]\]/g);
  add(/\[[^\]\n]*\]\([^)\n]*\)/g);
  add(/\{[^}\n]*\}/g);
  add(/<!--[\s\S]*?-->/g);
  add(/<[^>\n]+>/g);
  return ranges.sort((a, b) => a[0] - b[0]);
}

const inAnyRange = (i, ranges) => ranges.some(([s, e]) => i >= s && i < e);

/**
 * Which glossary keys does this body actually contain, ignoring protected regions?
 * Used by the validator to report registry entries no Chapter ever mentions.
 */
export function glossaryKeysIn(body, byForm, regex) {
  const ranges = protectedRanges(body);
  const found = new Set();
  for (const m of body.matchAll(regex)) {
    if (inAnyRange(m.index, ranges)) continue;
    if (!matchCaseOk(byForm, m[1])) continue;
    const key = byForm.get(m[1].toLowerCase());
    if (key) found.add(key);
  }
  return found;
}

/**
 * Wrap the FIRST occurrence of each glossary term in `[[g:key|as written]]`.
 *
 * First use per Chapter, not every use: 235 occurrences of "the Warp" across the
 * book do not want 235 dotted underlines. `skipKeys` carries the terms this Chapter
 * must leave alone — ones an author marked by hand, and the term's own
 * `full_treatment` Chapter, where the surrounding prose IS the definition.
 */
export function markGlossaryFirstUse(body, {
  byForm, regex, skipKeys = new Set(), chapterScoped = new Set(), perSection = true,
}) {
  const ranges = protectedRanges(body);
  const edits = [];
  const allMarked = new Set();
  // Two windows. Most terms reset at each Section, so a reader arriving deep in a
  // Chapter still gets the definition. A handful are too common for that: marking "the
  // Warp" once per Section produced forty dotted underlines across the book, which is
  // visual noise rather than help. Those carry `mark_scope: chapter` in the registry and
  // reset only once per Chapter.
  const doneChapter = new Set();
  let done = new Set();

  // Section boundaries, so the first-use window can reset at each `##`. The Section is
  // this book's addressable unit — it carries the anchor, it is what the contents tree
  // links to, and it is where a reader arriving from search lands. Resetting per
  // Chapter left anyone deep-linked into a later Section with no tooltip at all,
  // because the term had been marked screens above in a Section they never saw.
  const bounds = perSection
    ? [...body.matchAll(/^##\s+/gm)].map((m) => m.index)
    : [];
  let nextBound = 0;

  for (const m of body.matchAll(regex)) {
    while (nextBound < bounds.length && m.index >= bounds[nextBound]) {
      done = new Set();
      nextBound++;
    }
    if (!matchCaseOk(byForm, m[1])) continue;
    const key = byForm.get(m[1].toLowerCase());
    if (!key || skipKeys.has(key)) continue;
    const seen = chapterScoped.has(key) ? doneChapter : done;
    if (seen.has(key)) continue;
    if (inAnyRange(m.index, ranges)) continue;
    seen.add(key);
    allMarked.add(key);
    edits.push({ at: m.index, len: m[0].length, text: `[[g:${key}|${m[0]}]]` });
  }

  let out = body;
  for (const e of edits.reverse()) out = out.slice(0, e.at) + e.text + out.slice(e.at + e.len);
  return { text: out, marked: [...allMarked], marks: edits.length };
}

// ---------------------------------------------------------------------------
// Named terms the prose introduces but no registry defines
// ---------------------------------------------------------------------------
//
// House style bolds a term where it is introduced (**Arx Doctrine**, **Kasrs**). That
// makes bolded proper-noun phrases a usable signal for "the prose treats this as a
// term", and comparing them against the registries finds coverage gaps that no
// existing check could see — every earlier check asked only whether REGISTERED terms
// get used, never whether used terms get registered.
//
// Bolding marks introduction, which happens once, so it says nothing about reach. The
// validator therefore only reports candidates that appear in SEVERAL Chapters: a term
// introduced and used inside the one Chapter that explains it needs no glossary entry,
// and treating those as gaps produced a backlog six times larger than the real one.

const CONNECTIVE = new Set(['of', 'the', 'and', 'to', 'in', 'for']);

export function namedTermCandidates(body) {
  const out = new Set();
  for (const m of body.matchAll(/\*\*([^*\n]{3,60})\*\*/g)) {
    // Text BETWEEN two adjacent bold spans looks identical to a span: in
    // "…individual Chapters.** Some **operate as…" the capture is " Some ".
    // The tell is the whitespace just inside the asterisks — Markdown does not
    // read "** x **" as emphasis, so a real span never has it. This subsumes the
    // "At the" case that the trailing-connective rule below was added for.
    if (/^\s|\s$/.test(m[1])) continue;
    const term = m[1].trim().replace(/^(?:the|a|an)\s+/i, '').replace(/[.,;:!?'"]+$/, '').trim();
    if (term.length < 4) continue;
    if (!/^[A-Z]/.test(term)) continue;          // emphasis, not a name
    if (/[[\]^*|]/.test(term)) continue;         // stray markup
    const words = term.split(/\s+/);
    // A single bolded word ending in -ly is emphasis, not a proper noun. The prose
    // bolds "**Willingly**" as a rhetorical beat, and the check reported it as a
    // missing term. Multi-word phrases are exempt: a real name can contain one.
    if (words.length === 1 && /ly$/i.test(term)) continue;
    if (words.length > 4) continue;              // a clause, not a term
    if (!words.every((w, i) => /^[A-Z]/.test(w) || (i > 0 && CONNECTIVE.has(w.toLowerCase())))) continue;
    // A name never ends in a connective. "At the" is not a term — it is the text BETWEEN two
    // adjacent bold spans on one line, which the capture above cannot distinguish from a phrase.
    if (CONNECTIVE.has(words[words.length - 1].toLowerCase())) continue;
    out.add(term);
  }
  return out;
}

/** Does `term` occur in this body at all, bold or not, singular or plural? */
export function mentionsTerm(body, term) {
  const re = new RegExp(`(?<![\\p{L}\\p{N}\\-])${escapeRe(term)}(?:s|es)?(?![\\p{L}\\p{N}\\-])`, 'iu');
  return re.test(body.replace(/[*_`]/g, ''));
}

/**
 * Collect every [[...]] and [^...] in a body.
 * `offset` is the chapter's bodyOffset, so reported lines point into the real file.
 */
export function collectMarkup(body, offset = 0) {
  const links = [];
  const cites = [];
  body.split(/\r?\n/).forEach((line, i) => {
    const at = offset + i + 1;
    for (const m of line.matchAll(LINK_RE)) {
      links.push({ target: m[1].trim(), text: m[2]?.trim() ?? null, line: at });
    }
    for (const m of line.matchAll(CITE_RE)) {
      cites.push({ id: m[1], line: at });
    }
  });
  return { links, cites };
}
